//Skip Onboarding Screen
export const SKIP_ONBOARDING = 'SKIP_ONBOARDING';

//Screens Data
export const NAVIGATE_TO_SCREEN = 'NAVIGATE_TO_SCREEN';

//Browser Data
export const BROWSER_FAVORITES = 'BROWSER_FAVORITES';
export const BROWSER_HISTORYS = 'BROWSER_HISTORYS';
export const BROWSER_INCOGNITO_TABS = 'BROWSER_INCOGNITO_TABS';
export const BROWSER_TABS = 'BROWSER_TABS';
export const BROWSER_SETTINGS_SEARCHREGION = 'BROWSER_SETTINGS_SEARCHREGION';
export const BROWSER_SETTINGS_SAFESEARCH = 'BROWSER_SETTINGS_SAFESEARCH';
export const BROWSER_SETTINGS_AUTOCOMPLETE = 'BROWSER_SETTINGS_AUTOCOMPLETE';

